name: Prettier Format

on:
  push:
    branches:
      - 'master'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Create or switch to 'prettier' branch
      run: |
        git checkout -B prettier

    - name: Run Prettier
      run: npx prettier --write .

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git commit -m "Apply prettier formatting" || echo "No changes to commit"
        git push origin prettier --force

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        commit-message: "Apply prettier formatting"
        title: "Apply prettier formatting"
        body: "This PR applies prettier formatting to the codebase."
        branch: "prettier"
        base: "master"
