name: Prettier Format

on:
  push:
    branches-ignore:
      - 'master' # Avoid infinite loop of formatting and PRs

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier
      run: npx prettier --write .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Apply prettier formatting"
        title: "Apply prettier formatting"
        body: "This PR applies prettier formatting to the codebase."
        branch: "prettier-formatting"
        base: "master"
